version: '3.8'

services:
  server1:
    build: ./app
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  server2:
    build: ./app
    environment:
      - PORT=3002
    ports:
      - "3002:3002"

  nginx:
    image: nginx:latest
    volumes:
      - ./app/conf/loadbalancer.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/public:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - server1
      - server2